#tipe data boolean
print(True)
#tipe data string
print("ayo belajar python")
print('belajar phython sangat mudah')
#tipe data integer
print(20)
#tipe data float
print(3.14)
#tipe data hexadecimal
#print(9a)
#tipe data complex
print(5j)
#tipe data list
print([1,2,3,4,5])
print(("satu","dua","tiga"))
#tipe data dictionary
print({"nama":"budi",'umur':20})
#tipe data dictionary dimasukan ke dalam variable biodata
biodata={"nama":"andi",'umur':21} #peoses inisialisasi variable biodata
print(biodata) #proses pencetakan variabel data yang berisi variabel biodata
print(type(biodata)) #fungsi untuk mengecek jenis tipe data. akan tampil <class'dict'> yang berarti dict adalah tipe data dicionary