# variable adalah tempat penyimpanan data
# menaru / assignment nilai
a=10
x=5
panjang=1000
#pemanggilan pertama
print("nilai a=",a)
print("nilai x=",x)
print("nilai panjang=",panjang)
# penamaan
nilai_y=15 # dengan menggunakan underscore
juta10=10000000 # ini boleh
nilaiZ=17.5 # ini boleh
# pemanggilan kedua
print("nilaia=",a)
a=7
print("nilaia=",a)
# assigment indirect
b=a
print("nilaib=",b)
